var asylum = {
    "Syria": 60.4,
    "Central African Republic": 33.0,
    "South Sudan": 21.4,
    "Somalia": 17.1,
    "Colombia": 13.4,
    "Iraq": 11.7,
    "Afghanistan": 11.3,
    "Eritrea": 8.2,
    "Sudan": 7.7,
    "Georgia": 7.5,
    "Azerbaijan": 6.7,
    "Libya": 6.0,
    "Congo, Dem. Rep.": 0.0,
    "Bosnia and Herzegovina": 4.6,
    "Serbia": 4.4,
    "Burundi": 3.4,
    "Bhutan": 3.1,
    "Mali": 2.5,
    "Ukraine": 2.4,
    "Myanmar": 1.7,
    "St. Vincent and the Grenadines": 1.6,
    "Yemen, Rep.": 1.6,
    "Croatia": 1.3,
    "Mauritania": 1.0,
    "Pakistan": 1.0,
    "Rwanda": 0.9,
    "Albania": 0.9,
    "Sri Lanka": 0.8,
    "Gambia, The": 0.8,
    "Nigeria": 0.8,
    "Haiti": 0.7,
    "Armenia": 0.6,
    "Chad": 0.6,
    "St. Lucia": 0.5,
    "Uganda": 0.5,
    "Macedonia, FYR": 0.5,
    "El Salvador": 0.5,
    "Zimbabwe": 0.4,
    "Congo, Rep.": 0.4,
    "Liberia": 0.4,
    "Grenada": 0.4,
    "Vietnam": 0.3,
    "Angola": 0.3,
    "Philippines": 0.3,
    "Montenegro": 0.3,
    "Guinea": 0.3,
    "Senegal": 0.2,
    "Fiji": 0.2,
    "Guinea-Bissau": 0.2,
    "Honduras": 0.2,
    "Mongolia": 0.2,
    "Ethiopia": 0.2,
    "Togo": 0.2,
    "Iran, Islamic Rep.": 0.2,
    "Guatemala": 0.1,
    "Lebanon": 0.1,
    "Djibouti": 0.1,
    "Sierra Leone": 0.1,
    "Comoros": 0.1,
    "Lao PDR": 0.1,
    "Ghana": 0.1,
    "Guyana": 0.1,
    "Moldova": 0.1,
    "Tonga": 0.1,
    "Turkey": 0.1,
    "Cambodia": 0.1,
    "Cuba": 0.1,
    "Jamaica": 0.1,
    "Dominica": 0.1,
    "Kyrgyz Republic": 0.1,
    "Cameroon": 0.1,
    "Antigua and Barbuda": 0.1,
    "Russian Federation": 0.1,
    "Bahamas, The": 0.1,
    "St. Kitts and Nevis": 0.1,
    "Belarus": 0.1,
    "Namibia": 0.1,
    "Tuvalu": 0.1,
    "Nepal": 0.1,
    "Ecuador": 0.0,
    "Seychelles": 0.0,
    "Venezuela, RB": 0.0,
    "Trinidad and Tobago": 0.0,
    "Nicaragua": 0.0,
    "Barbados": 0.0,
    "Belize": 0.0,
    "Jordan": 0.0,
    "Bahrain": 0.0,
    "Kuwait": 0.0,
    "Mexico": 0.0,
    "Lesotho": 0.0,
    "Tunisia": 0.0,
    "Egypt, Arab Rep.": 0.0,
    "Estonia": 0.0,
    "Bulgaria": 0.0,
    "Kenya": 0.0,
    "Malawi": 0.0,
    "Equatorial Guinea": 0.0,
    "Swaziland": 0.0,
    "Palau": 0.0,
    "Monaco": 0.0,
    "Algeria": 0.0,
    "Turkmenistan": 0.0,
    "Uzbekistan": 0.0,
    "Bangladesh": 0.0,
    "Mauritius": 0.0,
    "Tajikistan": 0.0,
    "Kazakhstan": 0.0,
    "Burkina Faso": 0.0,
    "China": 0.0,
    "Peru": 0.0,
    "Marshall Islands": 0.0,
    "Gabon": 0.0,
    "Hungary": 0.0,
    "Solomon Islands": 0.0,
    "Israel": 0.0,
    "Romania": 0.0,
    "Morocco": 0.0,
    "Sao Tome and Principe": 0.0,
    "Dominican Republic": 0.0,
    "Botswana": 0.0,
    "Latvia": 0.0,
    "Czech Republic": 0.0,
    "Cabo Verde": 0.0,
    "Slovak Republic": 0.0,
    "Suriname": 0.0,
    "Costa Rica": 0.0,
    "Maldives": 0.0,
    "Benin": 0.0,
    "Andorra": 0.0,
    "Bolivia": 0.0,
    "Lithuania": 0.0,
    "Niger": 0.0,
    "Papua New Guinea": 0.0,
    "Indonesia": 0.0,
    "Korea, Dem. People\u00eas Rep.": 0.0,
    "Samoa": 0.0,
    "Mozambique": 0.0,
    "Uruguay": 0.0,
    "Malaysia": 0.0,
    "Kiribati": 0.0,
    "Poland": 0.0,
    "Zambia": 0.0,
    "Chile": 0.0,
    "Tanzania": 0.0,
    "Saudi Arabia": 0.0,
    "San Marino": 0.0,
    "Panama": 0.0,
    "India": 0.0,
    "Madagascar": 0.0,
    "Ireland": 0.0,
    "Paraguay": 0.0,
    "Timor-Leste": 0.0,
    "United Arab Emirates": 0.0,
    "Singapore": 0.0,
    "South Africa": 0.0,
    "United States": 0.0,
    "Slovenia": 0.0,
    "Greece": 0.0,
    "Iceland": 0.0,
    "Korea, Rep.": 0.0,
    "Malta": 0.0,
    "Qatar": 0.0,
    "Oman": 0.0,
    "Cyprus": 0.0,
    "Brazil": 0.0,
    "Argentina": 0.0,
    "Thailand": 0.0,
    "Belgium": 0.0,
    "New Zealand": 0.0,
    "Netherlands": 0.0,
    "Portugal": 0.0,
    "Luxembourg": 0.0,
    "Brunei Darussalam": 0.0,
    "Canada": 0.0,
    "Vanuatu": 0.0,
    "Denmark": 0.0,
    "United Kingdom": 0.0,
    "Germany": 0.0,
    "Italy": 0.0,
    "Norway": 0.0,
    "Spain": 0.0,
    "Sweden": 0.0,
    "Switzerland": 0.0,
    "Japan": 0.0,
    "France": 0.0,
    "Austria": 0.0,
    "Finland": 0.0,
    "Australia": 0.0,
    "Cote d'Ivoire": 0.0,
    "Liechtenstein": 0.0,
    "Nauru": 0.0
}